### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by simple-it** [joaovitoriasilva/endurain#162]
## Checklist

- [x] I have searched **existing issues** to make sure this bug hasn't already been reported.
- [x] I have checked the **documentation** at [https://docs.endurain.com](https://docs.endurain.com) and didn't find a solution.

## Description

On first run Endurain docker returns this error:

Error loading ASGI app. Could not import module "main".

## Expected Behavior

What did you expect to happen?
I expect Endurain docker runs
I ve alse see that the endurain database still empty

## Screenshots, logs or files

If applicable, add screenshots, logs or files to help explain your problem. If you do not wish to upload sensitive information to the issue you can send that info to [joao@endurain.com](joao@endurain.com).

```
INFO: UID=1000, GID=1000
INFO: Ownership adjusted for /app/backend/logs
INFO: Ownership adjusted for /app/backend/user_images
INFO: Ownership adjusted for /app/backend/files
INFO: Directory /app/backend/server_images does not exist, skipping.
INFO: Substituting MY_APP_ENDURAIN_HOST with http://192.168.0.208:8084
INFO: Starting FastAPI wih BEHIND_PROXY=false
ERROR:    Error loading ASGI app. Could not import module "main".
```

**Comment by joaovitoriasilva** [comment]
Hello. Thanks for reaching out. This will probably be a problem in the docker compose logic. Can you share your logic? Hide secrets pls

Thank you

**Comment by simple-it** [comment]
```
services:
  endurain:
    container_name: endurain
    image: ghcr.io/joaovitoriasilva/endurain:latest
    environment:
      - TZ=Europe/Lisbon
      - DB_TYPE=mariadb # mariadb or postgres
      - DB_HOST=mariadb # mariadb or postgres
      - DB_PORT=3307 # 3306 or 5432
      - DB_PASSWORD=changeme
      - SECRET_KEY=chnageme # openssl rand -hex 32
      - GEOCODES_MAPS_API=changeme
      - ENDURAIN_HOST=http://192.168.0.208:8084 # host or local ip (example: http://192.168.1.10:8080 or https://endurain.com), default is http://localhost:8080
      - BEHIND_PROXY=false # default value is false. Change to true if behind reverse proxy
    volumes:
      - ./endurain/backend/app:/app/backend # Configure volume if you want to edit the code locally by cloning the repo
      - ./endurain/backend/user_images:/app/backend/user_images # necessary for user image persistence on container image updates
      - ./endurain/backend/files/bulk_import:/app/backend/files/bulk_import # necessary to enable bulk import of activities. Place here your activities files
      - ./endurain/backend/files/processed:/app/backend/files/processed # necessary for processed original files persistence on container image updates
      - ./endurain/backend/logs:/app/backend/logs # log files for the backend
    ports:
      - "8084:8080" # Endurain port, change per your needs
    
     
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=endurain
      - MYSQL_USER=endurain
      - MYSQL_PASSWORD=changeme
    ports:
      - "3307:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    restart: unless-stopped


# adminer for DB manipulation - optional
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8085:8080
    restart: unless-stopped

# phpmyadmin for DB manipulation - optional
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8180:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
    restart: unless-stopped

networks:
  default:
    external: true
    name: endurain_network
```
