### ISSUE TITLE
Frontend wants to connect to "http://backend:80" despite I configured a different URI

### ISSUE THREAD

**Issue by vordenken** [joaovitoriasilva/endurain#62]
Hi @joaovitoriasilva ,
cool project! 
Wanted to implement it into my setup but unfortunately fail.
The frontend wants to load http://backend/api/v1/token but I changed its address in the variable to https://backend.endurain.myurl.tld .
I also tried different styles for the variables, with/without protocol/port but same error.

Heres the error in my browser:

```
[Error] Fetch API cannot load http://backend/api/v1/token due to access control checks.
```

Here's my docker-compose:

```
---

networks:
  backend_network:
  proxy:
    name: proxy
    external: true

services:
  frontend:
    container_name: frontend
    image: ghcr.io/joaovitoriasilva/endurain/frontend:latest
    environment:
      - MY_APP_BACKEND_PROTOCOL=https
      - MY_APP_BACKEND_HOST=backend.endurain.myurl.tld
      - MY_APP_STRAVA_CLIENT_ID=$MY_APP_STRAVA_CLIENT_ID
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.endurain.rule=Host(`endurain.myurl.tld`)"
      - "traefik.http.routers.endurain.entrypoints=websecure"
      - "traefik.http.routers.endurain.tls.certresolver=myresolver"
    networks:
      - proxy
      - backend_network
    restart: unless-stopped

  backend:
    container_name: backend
    image: ghcr.io/joaovitoriasilva/endurain/backend:latest
    environment:
      - TZ=Europe/Berlin
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_PASSWORD=$DB_PASSWORD
      - SECRET_KEY=$SECRET_KEY
      - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
      - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
      - STRAVA_AUTH_CODE=$STRAVA_AUTH_CODE
      - GEOCODES_MAPS_API=$GEOCODES_MAPS_API
      - FRONTEND_PROTOCOL=https
      - FRONTEND_HOST=endurain.myurl.tld
    volumes:
      - /mnt/docker/endurain/backend/user_images:/app/user_images
      - /mnt/docker/endurain/backend/files/bulk_import:/app/files/bulk_import
      - /mnt/docker/endurain/backend/files/processed:/app/files/processed
      - /mnt/docker/endurain/backend/logs:/app/logs
    depends_on:
      - postgres
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.endurainbacked.rule=Host(`backend.endurain.myurl.tld`)"
      - "traefik.http.routers.endurainbacked.entrypoints=websecure"
      - "traefik.http.routers.endurainbacked.tls.certresolver=myresolver"
    networks:
      - proxy
      - backend_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=endurain
      - POSTGRES_USER=endurain
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - /mnt/docker/endurain/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend_network  
```
