### ISSUE TITLE
UID / GID issue

### ISSUE THREAD

**Issue by Billos** [joaovitoriasilva/endurain#95]
Hello, 

This is my current compose: 

```yaml
services:
  endurain:
    container_name: endurain
    image: ghcr.io/joaovitoriasilva/endurain:v0.8.2
    environment:
      - UID=1001
      - GID=1001
...
```

Which gives me the following starting logs:

```
Checking ownership of necessary directories...
Adjusting ownership to match host UID (1000) and GID (1000)...
```

This makes it impossible for me to define a volume to store the images.

Is there something I am missing ?
